language: node_js
node_js: '12.16.3'
cache: npm 
services:
  - redis-server
install: 
  - npm i
env: 
  - PORT=4000 API_URL='http://localhost:4000' CORS_ORIGIN='http://localhost:8080' APP_SECRET='fake secret key' REDIS_URI='' DEBUG='app:*' REDIS_URI='redis://localhost:6379' EMAIL_SMTP=smtp.ethereal.email EMAIL_PORT=587 EMAIL_USER='tobin.hoeger@ethereal.email' EMAIL_PASS='zDm8pm8vMV4A6yv1FE'
script: 
  - npm run test
