version: '3'
services:
  api:
    build:   
      context: .
      dockerfile: api.Dockerfile
    ports:
     - "3000:3000"
    links:
     - db:redis
    environment:
      - REDIS_URI=redis://cache
    env_file:
      - .env
  mailer:
    build:   
      context: .
      dockerfile: mailer.Dockerfile
    links:
     - db:redis
    environment:
      - REDIS_URI=redis://cache
    env_file:
      - .env
  db:
    image: "redis"
    container_name: cache
